services:
  lab:
    build:
      dockerfile: ./lab/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
  frontend:
    image: node:18-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
  backend:
    build:
      dockerfile: ./lab/Dockerfile
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    command: poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
